[DRAFT] specVersion 3.0
SAP/ui5-project pull request #522
Opened 2022-12-06 12:10 UTC by d3xter666

JIRA: CPOUI5FOUNDATION-473

2022-12-12 08:22 UTC, matz3 requested changes
New tests for changes in specVersion 3.0 missing

2022-12-12 08:22 UTC, matz3 commented on lib/validation/schema/specVersion/kind/project.json
> +					"bundleDefinition": {
There are no changes to the `bundleDefinition`, so this section could be defined separately and then re-used instead of copied.

2022-12-13 13:51 UTC, d3xter666 commented
> New tests for changes in specVersion 3.0 missing

There are now tests to cover the new/modified properties

2022-12-14 07:33 UTC, d3xter666 commented on test/lib/validation/schema/__helper__/builder-bundleOptions.js
> + * Common test functionality for customConfiguration section in config
Done

2022-12-15 08:56 UTC, flovogt commented
LGTM

2022-12-19 10:35 UTC, matz3 commented
LGTM. Please use the [FEATURE] tag for title and commit message.

2022-12-20 08:59 UTC, matz3 approved these changes

2022-12-20 09:11 UTC, merged