[FIX] ui5Framework: Improve error handling for duplicate lib declaration
SAP/ui5-project pull request #578
Opened 2023-02-14 13:55 UTC by matz3

Fixes: https://github.com/SAP/ui5-tooling/issues/780

2023-02-15 06:50 UTC, d3xter666 commented on lib/graph/helpers/ui5Framework.js
> +		if (duplicateFrameworkProjectNames.length) {
Maybe `Array.some()` would suit better here:

```suggestion
			.some((name) => projectGraphProjectNames.includes(name));

		if (duplicateFrameworkProjectNames) {
```

2023-02-15 06:53 UTC, d3xter666 reviewed
LGTM

2023-02-15 14:34 UTC, RandomByte requested changes

2023-02-15 14:34 UTC, RandomByte commented on lib/graph/helpers/ui5Framework.js
> +				`Duplicate framework library definition(s) found in project ${projectGraph.getRoot().getName()}: ` +
```suggestion
				`Duplicate framework dependency definition(s) found for project ${projectGraph.getRoot().getName()}: ` +
```

2023-02-15 14:34 UTC, RandomByte commented on lib/graph/helpers/ui5Framework.js
> +				`${duplicateFrameworkProjectNames.join(", ")}. ` +
```suggestion
				`${duplicateFrameworkProjectNames.join(", ")}.\n` +
```
Line break for readability?

2023-02-15 14:34 UTC, RandomByte commented on lib/graph/helpers/ui5Framework.js
> +				`Note that this error could also come from transitive dependencies.`
```suggestion
				`Framework libraries should only be referenced via ui5.yaml configuration. ` +
				`Neither the root project, nor any of its dependencies should include them as direct ` +
				`dependencies (e.g. via package.json).`
```

What do you think? I'm not sure how common the term "transitive dependencies" is.

2023-02-16 11:12 UTC, RandomByte approved these changes

2023-02-16 12:47 UTC, merged